"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserInput = exports.User = exports.FeedInput = exports.Feed = exports.CategoryInput = exports.Category = exports.AuthorInput = exports.Author = exports.ArticleInput = exports.Article = void 0;
const article_1 = require("./model/article");
Object.defineProperty(exports, "Article", { enumerable: true, get: function () { return article_1.Article; } });
Object.defineProperty(exports, "ArticleInput", { enumerable: true, get: function () { return article_1.ArticleInput; } });
const author_1 = require("./model/author");
Object.defineProperty(exports, "Author", { enumerable: true, get: function () { return author_1.Author; } });
Object.defineProperty(exports, "AuthorInput", { enumerable: true, get: function () { return author_1.AuthorInput; } });
const category_1 = require("./model/category");
Object.defineProperty(exports, "Category", { enumerable: true, get: function () { return category_1.Category; } });
Object.defineProperty(exports, "CategoryInput", { enumerable: true, get: function () { return category_1.CategoryInput; } });
const feed_1 = require("./model/feed");
Object.defineProperty(exports, "Feed", { enumerable: true, get: function () { return feed_1.Feed; } });
Object.defineProperty(exports, "FeedInput", { enumerable: true, get: function () { return feed_1.FeedInput; } });
const user_1 = require("./model/user");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_1.User; } });
Object.defineProperty(exports, "UserInput", { enumerable: true, get: function () { return user_1.UserInput; } });
